blank_issues_enabled: true
contact_links:
  - name: LIGHT LPCA Community
    url: https://github.com/LIGHTLPCA
    about: Visit the LIGHT LPCA organization page for community discussions and other projects.
